# Generated by Django 5.0.4 on 2024-07-08 16:50

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_cid_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=50, prefix='', unique=True),
        ),
    ]
