# Generated by Django 5.0.4 on 2024-07-08 19:21

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_category_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghi12345', editable=False, length=10, max_length=30, prefix='pid', unique=True),
        ),
    ]
