# Generated by Django 5.0.4 on 2024-07-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_productimages_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='Product',
            new_name='product',
        ),
    ]
